### PR TITLE
Added slot support for buttons

### PR DESCRIPTION
**Pull request by lochstar**
Hi,

I've added support for named slots for each key in a layout. This enables you to render SVGs, images or whatever you'd like instead of plain text keys. This should close off https://github.com/martywallace/vue-keyboard/issues/14 and does not break existing functionality.

Slots use the action name for named actions, or the value for all other keys.

Example usage:

```vue
<vue-keyboard
  v-show="keyboardVisible"
  v-model="keyboardInput"
  :layouts="compactLayout"
>
  <template #backspace>
    <font-awesome icon="backspace" />
  </template>
  <template #q>
    <img src="q.png">
  </template>
</vue-keyboard>
```

I've also added the `key` attribute on the `v-for` loops as it's generally recommended and my linter complains. If you'd rather I remove this please let me know.

### CODE REVIEW

**Comment by martywallace** [comment]
That's pretty sweet, thanks a lot.

**Comment by gchoza** [comment]
Is there a working example? I cannot make slots or any CSS changes work. Using version 3.1.0.

            <keyboard
              v-show="dobActive"
              @input="changed"
              @today="today"
              @minus="minus"
              @plus="plus"
              layouts="/{-1:minus}{today:today}{+1:plus}/|123|456|789|{clr:clear}0{del:backspace}"
              v-model="patDOB"
            >
              <template #backspace
                >
              </template>
            </keyboard>


Everything is working but I cannot make any CSS changes to the keyboard buttons.

I've also tried the following to no effect:

`.vue-keyboard-key[data-action="backspace"]{
  font-size: 59px;
 }`

**Comment by gchoza** [comment]
Having trouble using slots. I can make CSS take effect by using v-deep: (::v-deep .vue-keyboard button {}) but cannot use slots. I may be missing something obvious. Using version 3.1.0.


            <keyboard
              v-show="dobActive"
              @input="changed"
              @today="today"
              @minus="minus"
              @plus="plus"
              layouts="/{-1:minus}{today:today}{+1:plus}/|123|456|789|{clr:clear}0{del:backspace}"
              v-model="patDOB"
            >
              <template #backspace
                >
              </template>
            </keyboard>

import keyboard from "vue-keyboard";
  components: { keyboard },

**Comment by lochstar** [comment]
Hey @gchoza, 3.1.0 was released Jun 2017 and this PR was made this year. Unless @martywallace can publish an update, you'll have to checkout master manually in your project to use this feature.

**Comment by gchoza** [comment]
Thanks, that explains it. I copied master and I'm OK.
I'll keep checking to see when there's an update.
This is a very nice keyboard. Thank you @martywallace !

@lochstar thanks for helping.

**Comment by KennyChan94** [comment]
i clone this git to my project and successfully making it run on my site but im still unable to change the backspace with an image

<Keyboard
                v-model="input"
                @custom="custom"
                @input="changed"
                :layouts="[
                    '123|456|789|0{Del:backspace}|{Confirm:custom}{Cancel:custom}'
                ]"
                :maxlength="16"
            >
                <template #backspace>
                    
                </template>
            </Keyboard>


Help me pleaseeee

**Pull request merged**
